# BÀI TẬP: TITANIC
**Nguồn:** kaggle.com/c/titanic (891 dòng)

In [18]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')

csv_path = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [19]:
# TODO
# DATA SIZE
df.shape

(891, 15)

In [20]:
# column names
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [21]:
df.columns.to_list()

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone']

In [22]:
# data types
df.dtypes

survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

## A.2. Missing values & Duplicate data

In [23]:
# TODO
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [24]:
df.duplicated

<bound method DataFrame.duplicated of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]>

In [36]:
df.duplicated().sum()

np.int64(107)

## A.3. Invalid values

In [38]:
# TODO
invalid_age = df[(df['age'] < 10) | (df['age'] > 100)]
print(invalid_age)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
7           0       3    male  2.00      3      1  21.0750        S   Third
10          1       3  female  4.00      1      1  16.7000        S   Third
16          0       3    male  2.00      4      1  29.1250        Q   Third
24          0       3  female  8.00      3      1  21.0750        S   Third
43          1       2  female  3.00      1      2  41.5792        C  Second
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
827         1       2    male  1.00      0      2  37.0042        C  Second
831         1       2    male  0.83      1      1  18.7500        S  Second
850         0       3    male  4.00      4      2  31.2750        S   Third
852         0       3  female  9.00      1      1  15.2458        C   Third
869         1       3    male  4.00      1      1  11.1333        S   Third

       who  adult_male deck  embark_town alive  alone
7    child       False  NaN  Southampton    no  False
10   child       False    G  Southampton   yes  False
16   child       False  NaN   Queenstown    no  False
24   child       False  NaN  Southampton    no  False
43   child       False  NaN    Cherbourg   yes  False
..     ...         ...  ...          ...   ...    ...
827  child       False  NaN    Cherbourg   yes  False
831  child       False  NaN  Southampton   yes  False
850  child       False  NaN  Southampton    no  False
852  child       False  NaN    Cherbourg    no  False
869  child       False  NaN  Southampton   yes  False

[62 rows x 15 columns]

## A.4. Create a new column
Tạo cột `family_size` = sibsp + parch + 1.

In [40]:
# TODO
df['family_size'] = df['sibsp'] + df['parch'] + 1
df[['sibsp', 'parch', 'family_size']].head()

   sibsp  parch  family_size
0      1      0            2
1      1      0            2
2      0      0            1
3      1      0            2
4      0      0            1

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [45]:
df.describe("")

,survived,pclass,age,sibsp,parch,fare,family_size
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,1.904602
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,1.613459
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,1.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,11.000000

In [43]:
# Median cho Age và Fare
median_age = df['age'].median()
median_fare = df['fare'].median()
print("Median Age:", median_age)
print("Median Fare:", median_fare)

Median Age: 28.0
Median Fare: 14.4542

In [42]:
# Mode cho Age và Fare
mode_age = df['age'].mode()[0]
mode_fare = df['fare'].mode()[0]
print("Mode Age:", mode_age)
print("Mode Fare:", mode_fare)

Mode Age: 24.0
Mode Fare: 8.05

In [41]:
# TODO
# Mean cho Age và Fare
mean_age = df['age'].mean()
mean_fare = df['fare'].mean()
print("Mean Age:", mean_age)
print("Mean Fare:", mean_fare)

Mean Age: 29.69911764705882
Mean Fare: 32.204207968574636

## Group 2 — Dispersion

In [47]:
# TODO
var_age = df['age'].var()
std_age = df['age'].std()
range_age = df['age'].max() - df['age'].min()

print("Variance (Age):", var_age)
print("Standard Deviation (Age):", std_age)
print("Range (Age):", range_age)

var_fare = df['fare'].var()
std_fare = df['fare'].std()
range_fare = df['fare'].max() - df['fare'].min()

print("Variance (Fare):", var_fare)
print("Standard Deviation (Fare):", std_fare)
print("Range (Fare):", range_fare)

Variance (Age): 211.01912474630802
Standard Deviation (Age): 14.526497332334042
Range (Age): 79.58
Variance (Fare): 2469.436845743116
Standard Deviation (Fare): 49.6934285971809
Range (Fare): 512.3292

## Group 3 — Location and Shape

In [48]:
# TODO
quantiles_age = df['age'].quantile([0.25, 0.5, 0.75])
skewness_age = df['age'].skew()
kurtosis_age = df['age'].kurtosis()

print("Quantiles (Age):\n", quantiles_age)
print("Skewness (Age):", skewness_age)
print("Kurtosis (Age):", kurtosis_age)

Quantiles (Age):
 0.25    20.125
0.50    28.000
0.75    38.000
Name: age, dtype: float64
Skewness (Age): 0.38910778230082704
Kurtosis (Age): 0.17827415364210353

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Hạng vé nào có tỷ lệ sống sót cao nhất, chênh lệch bao nhiêu so với hạng thấp nhất?

In [49]:

# TODO
# Tỷ lệ sống sót theo hạng vé
survival_by_class = df.groupby('class')['survived'].mean().sort_values(ascending=False)
print("Tỷ lệ sống sót theo hạng vé:\n", survival_by_class)

# Chênh lệch giữa cao nhất và thấp nhất
diff_class = survival_by_class.max() - survival_by_class.min()
print("Chênh lệch giữa hạng cao nhất và thấp nhất:", diff_class)

Tỷ lệ sống sót theo hạng vé:
 class
First     0.629630
Second    0.472826
Third     0.242363
Name: survived, dtype: float64
Chênh lệch giữa hạng cao nhất và thấp nhất: 0.3872671041713812

## Câu hỏi 2: Giới tính hay hạng vé ảnh hưởng đến sống sót mạnh hơn?

In [50]:
# TODO
# Tỷ lệ sống sót theo giới tính
survival_by_sex = df.groupby('sex')['survived'].mean()
print("Tỷ lệ sống sót theo giới tính:\n", survival_by_sex)

# TODO
# So sánh độ chênh lệch
diff_sex = survival_by_sex.max() - survival_by_sex.min()
print("Chênh lệch giữa giới tính:", diff_sex)

Tỷ lệ sống sót theo giới tính:
 sex
female    0.742038
male      0.188908
Name: survived, dtype: float64
Chênh lệch giữa giới tính: 0.5531300709799203

## Câu hỏi 3: Vé đắt hơn có thực sự sống sót cao hơn không?

In [51]:
# TODO
# Tính tương quan giữa fare và survived
corr_fare_survived = df[['fare','survived']].corr().iloc[0,1]
print("Tương quan giữa Fare và Survived:", corr_fare_survived)

Tương quan giữa Fare và Survived: 0.2573065223849626

## Câu hỏi 4: Gia đình đông người có ảnh hưởng đến khả năng sống sót không?

In [52]:
# TODO
# Tỷ lệ sống sót theo family_size
survival_by_family = df.groupby('family_size')['survived'].mean()
print("Tỷ lệ sống sót theo family_size:\n", survival_by_family)

Tỷ lệ sống sót theo family_size:
 family_size
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: survived, dtype: float64

## Câu hỏi 5: Cảng lên tàu (embark_town) nào có tỷ lệ sống sót cao nhất?

In [53]:
# TODO
# Tỷ lệ sống sót theo embark_town
survival_by_embark = df.groupby('embark_town')['survived'].mean().sort_values(ascending=False)
print("Tỷ lệ sống sót theo cảng lên tàu:\n", survival_by_embark)

Tỷ lệ sống sót theo cảng lên tàu:
 embark_town
Cherbourg      0.553571
Queenstown     0.389610
Southampton    0.336957
Name: survived, dtype: float64

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể về dữ liệu Titanic.

-Hành khách hạng First Class có tỷ lệ sống sót cao nhất, chênh lệch lớn so với Third Class.
-Nữ giới có tỷ lệ sống sót cao hơn nam rất rõ rệt.
-Vé đắt hơn thường đi kèm khả năng sống sót cao hơn.
-Gia đình nhỏ (2–4 người) có tỷ lệ sống sót cao hơn đi một mình hoặc quá đông.
-Cảng Cherbourg có tỷ lệ sống sót cao nhất trong ba cảng lên tàu.